name: Migrate DB

on:
  workflow_dispatch:  # чтобы можно было запускать вручную
  push:
    branches:
      - main
      - master
      - uploadOrder

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Go deps
        run: go mod tidy

      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/myapp?sslmode=disable
        run: go run ./cmd/migrate/migration.go